MODEL:
  PRETRAIN_CHOICE: "imagenet"
  NAME: 'resnet50'  # name of backbone
  NUM_EMB: 64
  EMB_DIM: 128

DATASETS:
  NAMES: 'msvr310' # support ['rgbir', 'msvr310', 'wmveid863']

INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST: [128, 256]
  PROB: 0.5
  RE_PROB: 0.4
  PADDING: 10
  USE_CHANNEL_ERASE: False
  CHANNEL_RE_PROB: 0.3
  ADAPT_GRAY_PROB: 0.3

DATALOADER: 
  SAMPLER: 'softmax' 
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  METHOD: 'agw' 
  RANDOM_SEED: 42
  RESUME: False
  GPU_ID: ('0')

  MAX_EPOCHS: 100
  VAL_EPOCHS: 75
  BASE_LR: 0.1

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMGS_PER_BATCH: 32

  STEPS: [20, 50] 
  GAMMA: 0.1 

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 400 
  LOG_PERIOD: 15 
  EVAL_PERIOD: 50 

TEST:
  IMGS_PER_BATCH: 16
  WEIGHT: "output"

OUTPUT_DIR: 'output'